all:
	python gen_data_v2.py

val: 
	python gen_data_v2.py --val

dbg:
	python -m pdb gen_data_v2.py

rmfile:
	rm equations.txt; rm solutions.txt; rm poly_labels.txt;

rmdir:
	rm -rf data; rm -rf label; rm -rf equations
